openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/palabra/{clave}:
    get:
      operationId: retrieveGetPutPalabra
      description: "M\xE9todo para obtener una palabra del cat\xE1logo"
      parameters:
      - name: clave
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    put:
      operationId: updateGetPutPalabra
      description: "M\xE9todo para actualizar una palabra del cat\xE1logo"
      parameters:
      - name: clave
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/palabra/:
    post:
      operationId: createPostPalabra
      description: "M\xE9todo para agregar una palabra al cat\xE1logo"
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
