# Generated by Django 4.2.7 on 2023-12-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catalogo_palabras',
            new_name='CatalogoPalabras',
        ),
    ]
